# Generated by Django 3.1.3 on 2020-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url_product', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('store', models.CharField(max_length=200)),
                ('nutriscore', models.IntegerField()),
                ('nutriscore_grad', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('url_api', models.URLField()),
                ('categories_id', models.ManyToManyField(related_name='_product_categories_id_+', to='product.Category')),
            ],
        ),
    ]
