# Generated by Django 3.1.3 on 2020-11-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201110_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='api_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
