# Generated by Django 3.1.3 on 2020-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category_ids',
            field=models.ManyToManyField(related_name='_product_category_ids_+', to='product.Category'),
        ),
    ]
