# Generated by Django 3.1.3 on 2020-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201110_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_ids',
            field=models.ManyToManyField(to='product.Category'),
        ),
    ]
