# Generated by Django 3.1.3 on 2020-11-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201112_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat_g',
            field=models.CharField(default=0.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fat_level',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='salt_g',
            field=models.CharField(default=0.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='salt_level',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='satured_fat_g',
            field=models.CharField(default=0.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='satured_fat_level',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_g',
            field=models.CharField(default=0.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_level',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
