# Generated by Django 3.1.3 on 2020-11-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201118_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_level',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_level',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='satured_fat_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='satured_fat_level',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_level',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
